export type DesktopSettings = Record<string, string>;

export type DesktopSettingInput =
    | 'text'
    | 'password'
    | 'number'
    | 'toggle'
    | 'select'
    | 'textarea';

export interface DesktopSettingOption {
    label: string;
    value: string;
}

export interface DesktopSettingDefinition {
    key: string;
    label: string;
    description: string;
    group: string;
    input: DesktopSettingInput;
    placeholder?: string;
    options?: DesktopSettingOption[];
}

const toggleOptions: DesktopSettingOption[] = [
    { label: 'Enabled', value: '1' },
    { label: 'Disabled', value: '0' },
];

export const DESKTOP_SETTING_DEFINITIONS: DesktopSettingDefinition[] = [
    {
        key: 'NVIDIA_API_KEY',
        label: 'NVIDIA API Key',
        description: 'API key used for NVIDIA NIM transcription and chat cleanup.',
        group: 'Models',
        input: 'password',
        placeholder: 'nvapi-...',
    },
    {
        key: 'NVIDIA_WHISPER_MODEL',
        label: 'NVIDIA Whisper Model',
        description: 'Transcription model sent to NVIDIA NIM audio transcription.',
        group: 'Models',
        input: 'text',
        placeholder: 'openai/whisper-large-v3',
    },
    {
        key: 'NVIDIA_CHAT_MODEL',
        label: 'NVIDIA Chat Model',
        description: 'Chat model used for smart cleanup and command interpretation.',
        group: 'Models',
        input: 'text',
        placeholder: 'nvidia/nemotron-3-8b-instruct',
    },
    {
        key: 'HOTKEY',
        label: 'Global Hotkey',
        description: 'Hold this key to start dictation and release to stop.',
        group: 'General',
        input: 'text',
        placeholder: 'F9',
    },
    {
        key: 'SMART_EDIT',
        label: 'Smart Edit',
        description: 'Enable transcript cleanup after transcription.',
        group: 'General',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'SMART_MODE',
        label: 'Smart Mode',
        description: 'Choose heuristic cleanup or LLM-powered cleanup.',
        group: 'General',
        input: 'select',
        options: [
            { label: 'LLM', value: 'llm' },
            { label: 'Heuristic', value: 'heuristic' },
        ],
    },
    {
        key: 'LLM_ALWAYS_CLEAN',
        label: 'Always LLM Clean',
        description: 'Clean every utterance with the LLM instead of only likely command edits.',
        group: 'General',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'PASTE_MODE',
        label: 'Paste Mode',
        description: 'Choose whether pasted output is full text or delta updates.',
        group: 'General',
        input: 'select',
        options: [
            { label: 'Delta', value: 'delta' },
            { label: 'Full', value: 'full' },
        ],
    },
    {
        key: 'PASTE_BACKEND',
        label: 'Paste Backend',
        description: 'Backend used to inject transcribed text into the active app.',
        group: 'General',
        input: 'select',
        options: [
            { label: 'Auto', value: 'auto' },
            { label: 'X11', value: 'x11' },
            { label: 'Keyboard', value: 'keyboard' },
            { label: 'Pynput', value: 'pynput' },
            { label: 'Xdotool', value: 'xdotool' },
            { label: 'Osascript', value: 'osascript' },
        ],
    },
    {
        key: 'HOTKEY_BACKEND',
        label: 'Hotkey Backend',
        description: 'Backend used to listen for the global hotkey.',
        group: 'General',
        input: 'select',
        options: [
            { label: 'Auto', value: 'auto' },
            { label: 'X11', value: 'x11' },
            { label: 'Pynput', value: 'pynput' },
            { label: 'Keyboard', value: 'keyboard' },
        ],
    },
    {
        key: 'RESET_TRANSCRIPT_EACH_RECORDING',
        label: 'Reset Transcript Each Recording',
        description: 'Clear the transcript area each time recording starts.',
        group: 'General',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'INSTANT_REFINE',
        label: 'Instant Refine',
        description: 'Prefer immediate paste followed by a refined update.',
        group: 'General',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'DICTATION_MODE',
        label: 'Dictation Mode',
        description: 'Trade speed for transcript accuracy.',
        group: 'Dictation',
        input: 'select',
        options: [
            { label: 'Speed', value: 'speed' },
            { label: 'Balanced', value: 'balanced' },
            { label: 'Accurate', value: 'accurate' },
        ],
    },
    {
        key: 'CLEANUP_LEVEL',
        label: 'Cleanup Level',
        description: 'How aggressive the transcript cleanup should be.',
        group: 'Dictation',
        input: 'select',
        options: [
            { label: 'Basic', value: 'basic' },
            { label: 'Balanced', value: 'balanced' },
            { label: 'Aggressive', value: 'aggressive' },
        ],
    },
    {
        key: 'DEFAULT_TONE',
        label: 'Default Tone',
        description: 'Default tone used for rewrite and cleanup actions.',
        group: 'Dictation',
        input: 'text',
        placeholder: 'polite',
    },
    {
        key: 'DEFAULT_LANGUAGE',
        label: 'Default Language',
        description: 'Default language used for transcript cleanup and rewriting.',
        group: 'Dictation',
        input: 'text',
        placeholder: 'english',
    },
    {
        key: 'ACTIVE_PROFILE',
        label: 'Active Profile',
        description: 'Profile id used to customize behavior per workflow.',
        group: 'Dictation',
        input: 'text',
        placeholder: 'default',
    },
    {
        key: 'ACTIVE_APP',
        label: 'Active App Override',
        description: 'Optional active app name override for profile routing.',
        group: 'Dictation',
        input: 'text',
    },
    {
        key: 'SAMPLE_RATE',
        label: 'Sample Rate',
        description: 'Target audio sample rate used by the audio pipeline.',
        group: 'Audio',
        input: 'number',
        placeholder: '16000',
    },
    {
        key: 'CHANNELS',
        label: 'Channels',
        description: 'Number of audio channels captured for transcription.',
        group: 'Audio',
        input: 'number',
        placeholder: '1',
    },
    {
        key: 'TRIM_SILENCE',
        label: 'Trim Silence',
        description: 'Remove silence during audio preprocessing.',
        group: 'Audio',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'SILENCE_THRESHOLD',
        label: 'Silence Threshold',
        description: 'Threshold used to decide what counts as silence.',
        group: 'Audio',
        input: 'number',
        placeholder: '0.02',
    },
    {
        key: 'STREAMING_ENABLED',
        label: 'Streaming Preview',
        description: 'Enable real-time transcription preview while recording.',
        group: 'Streaming',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'STREAMING_CHUNK_DURATION',
        label: 'Chunk Duration',
        description: 'Streaming audio chunk duration in seconds.',
        group: 'Streaming',
        input: 'number',
        placeholder: '1.5',
    },
    {
        key: 'STREAMING_CHUNK_OVERLAP',
        label: 'Chunk Overlap',
        description: 'Overlap ratio between streaming chunks for accuracy.',
        group: 'Streaming',
        input: 'number',
        placeholder: '0.3',
    },
    {
        key: 'STREAMING_MIN_CHUNKS',
        label: 'Minimum Chunks',
        description: 'Minimum chunks before a streaming preview is shown.',
        group: 'Streaming',
        input: 'number',
        placeholder: '2',
    },
    {
        key: 'STREAMING_FINAL_PASS',
        label: 'Final Pass',
        description: 'Run a final accuracy pass after recording completes.',
        group: 'Streaming',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'MODE',
        label: 'Operation Mode',
        description: 'Choose between standard dictation mode and agent mode.',
        group: 'Agent',
        input: 'select',
        options: [
            { label: 'Dictation', value: 'dictation' },
            { label: 'Agent', value: 'agent' },
        ],
    },
    {
        key: 'AGENT_AUTO_DETECT',
        label: 'Auto Detect Agent Mode',
        description: 'Switch into agent mode automatically based on speech content.',
        group: 'Agent',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'AGENT_OUTPUT_FORMAT',
        label: 'Agent Output Format',
        description: 'Preferred format for agent-mode responses.',
        group: 'Agent',
        input: 'select',
        options: [
            { label: 'Structured', value: 'structured' },
            { label: 'Markdown', value: 'markdown' },
            { label: 'Plain', value: 'plain' },
        ],
    },
    {
        key: 'AGENT_WEBHOOK_URL',
        label: 'Agent Webhook URL',
        description: 'Webhook used for agent-mode integrations.',
        group: 'Agent',
        input: 'text',
        placeholder: 'https://...',
    },
    {
        key: 'AGENT_IDE_INTEGRATION',
        label: 'IDE Integration',
        description: 'Enable IDE integration for agent mode.',
        group: 'Agent',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'AGENT_ENDPOINTS',
        label: 'Agent Endpoints JSON',
        description: 'JSON object containing configured agent endpoints.',
        group: 'Agent',
        input: 'textarea',
        placeholder: '{"cursor":"http://localhost:9333"}',
    },
    {
        key: 'SPEC_MODE_ENABLED',
        label: 'Specification Mode',
        description: 'Enable specification-driven workflow support.',
        group: 'Specification',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'SPEC_TEMPLATE',
        label: 'Spec Template',
        description: 'Default template used for new specifications.',
        group: 'Specification',
        input: 'select',
        options: [
            { label: 'Standard', value: 'standard' },
            { label: 'Minimal', value: 'minimal' },
            { label: 'Detailed', value: 'detailed' },
            { label: 'OpenSpec', value: 'openspec' },
            { label: 'Luna', value: 'luna' },
            { label: 'GitHub', value: 'github' },
        ],
    },
    {
        key: 'SPEC_AUTO_DETECT_INTENT',
        label: 'Auto Detect Intent',
        description: 'Automatically detect whether speech is spec, code, or docs oriented.',
        group: 'Specification',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'SPEC_FORMAT',
        label: 'Spec Format',
        description: 'Default export format for specifications.',
        group: 'Specification',
        input: 'select',
        options: [
            { label: 'Standard', value: 'standard' },
            { label: 'OpenSpec', value: 'openspec' },
            { label: 'Luna', value: 'luna' },
            { label: 'GitHub', value: 'github' },
        ],
    },
    {
        key: 'SPEC_STORAGE_ENABLED',
        label: 'Spec Storage',
        description: 'Enable local storage and versioning for specifications.',
        group: 'Specification',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'WORKFLOW_FORMAT',
        label: 'Workflow Format',
        description: 'Workflow format for specification-driven work.',
        group: 'Specification',
        input: 'select',
        options: [
            { label: 'OpenSpec', value: 'openspec' },
            { label: 'Luna', value: 'luna' },
            { label: 'GitHub Spec Kit', value: 'github-spec-kit' },
        ],
    },
    {
        key: 'CLI_AUTO_DETECT',
        label: 'CLI Auto Detect',
        description: 'Auto-detect CLI and terminal contexts.',
        group: 'CLI',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'CLI_STRIP_NEWLINES',
        label: 'Strip Newlines',
        description: 'Strip automatic newlines in CLI mode.',
        group: 'CLI',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'CLI_NEWLINE_KEYWORD',
        label: 'Newline Keyword',
        description: 'Phrase that inserts a newline in CLI mode.',
        group: 'CLI',
        input: 'text',
        placeholder: 'new line',
    },
    {
        key: 'GRAMMAR_PRESERVE_CODE',
        label: 'Preserve Code',
        description: 'Preserve code snippets during grammar correction.',
        group: 'Grammar',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'GRAMMAR_PRESERVE_TECHNICAL',
        label: 'Preserve Technical Terms',
        description: 'Preserve technical terminology during grammar correction.',
        group: 'Grammar',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'PERSONAL_DICTIONARY_PATH',
        label: 'Personal Dictionary Path',
        description: 'Optional custom dictionary file path.',
        group: 'Files',
        input: 'text',
    },
    {
        key: 'SNIPPETS_PATH',
        label: 'Snippets Path',
        description: 'Optional snippets file path.',
        group: 'Files',
        input: 'text',
    },
    {
        key: 'PROFILE_BUNDLE_PATH',
        label: 'Profile Bundle Path',
        description: 'Optional imported profile bundle path.',
        group: 'Files',
        input: 'text',
    },
    {
        key: 'FLOATING_WIDTH',
        label: 'Floating Width',
        description: 'Width of the floating widget window.',
        group: 'Floating UI',
        input: 'number',
        placeholder: '180',
    },
    {
        key: 'FLOATING_HEIGHT',
        label: 'Floating Height',
        description: 'Height of the floating widget window.',
        group: 'Floating UI',
        input: 'number',
        placeholder: '44',
    },
    {
        key: 'FLOATING_BAR_COUNT',
        label: 'Floating Bar Count',
        description: 'Number of visualizer bars in the floating widget.',
        group: 'Floating UI',
        input: 'number',
        placeholder: '5',
    },
    {
        key: 'FLOATING_CLOSE_BUTTON',
        label: 'Floating Close Button',
        description: 'Show a close button on the floating widget.',
        group: 'Floating UI',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'FLOATING_THEME',
        label: 'Floating Theme',
        description: 'Visual theme used by the floating widget.',
        group: 'Floating UI',
        input: 'select',
        options: [
            { label: 'Professional Minimal', value: 'professional_minimal' },
            { label: 'High Contrast', value: 'high_contrast' },
        ],
    },
    {
        key: 'FLOATING_MOTION_PROFILE',
        label: 'Floating Motion Profile',
        description: 'Animation intensity profile for the floating widget.',
        group: 'Floating UI',
        input: 'select',
        options: [
            { label: 'Expressive', value: 'expressive' },
            { label: 'Balanced', value: 'balanced' },
            { label: 'Reduced', value: 'reduced' },
        ],
    },
    {
        key: 'FLOATING_GLOW_INTENSITY',
        label: 'Glow Intensity',
        description: 'Glow strength multiplier for the floating widget.',
        group: 'Floating UI',
        input: 'number',
        placeholder: '1.0',
    },
    {
        key: 'FLOATING_BAR_RADIUS',
        label: 'Bar Radius',
        description: 'Roundness multiplier for floating widget bars.',
        group: 'Floating UI',
        input: 'number',
        placeholder: '1.0',
    },
    {
        key: 'FLOATING_BORDER_ALPHA',
        label: 'Border Alpha',
        description: 'Border opacity for the floating widget shell.',
        group: 'Floating UI',
        input: 'number',
        placeholder: '72',
    },
    {
        key: 'FLOATING_UI_STYLE',
        label: 'Floating UI Style',
        description: 'Overall style for the floating widget.',
        group: 'Floating UI',
        input: 'select',
        options: [
            { label: 'Modern', value: 'modern' },
            { label: 'Classic', value: 'classic' },
        ],
    },
    {
        key: 'FLOATING_ACCENT_COLOR',
        label: 'Floating Accent Color',
        description: 'Accent color used in the modern floating UI.',
        group: 'Floating UI',
        input: 'select',
        options: [
            { label: 'Blue', value: 'blue' },
            { label: 'Purple', value: 'purple' },
            { label: 'Green', value: 'green' },
        ],
    },
    {
        key: 'FLOATING_GLASSMORPHISM',
        label: 'Glassmorphism',
        description: 'Enable glassmorphism effects in the floating UI.',
        group: 'Floating UI',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'FLOATING_ANIMATIONS',
        label: 'Floating Animations',
        description: 'Enable floating UI animations.',
        group: 'Floating UI',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'FLOATING_REDUCED_MOTION',
        label: 'Reduced Motion',
        description: 'Reduce floating UI motion for accessibility.',
        group: 'Floating UI',
        input: 'toggle',
        options: toggleOptions,
    },
    {
        key: 'FLOATING_LAYOUT',
        label: 'Floating Layout',
        description: 'Layout style used by the floating widget.',
        group: 'Floating UI',
        input: 'select',
        options: [
            { label: 'Circular', value: 'circular' },
            { label: 'Pill', value: 'pill' },
            { label: 'Card', value: 'card' },
        ],
    },
];

const desktopSettingDefaults: DesktopSettings = {
    NVIDIA_API_KEY: '',
    HOTKEY: 'f9',
    SMART_EDIT: '1',
    SMART_MODE: 'llm',
    LLM_ALWAYS_CLEAN: '1',
    PASTE_MODE: 'delta',
    PASTE_BACKEND: 'auto',
    HOTKEY_BACKEND: 'auto',
    FLOATING_WIDTH: '180',
    FLOATING_HEIGHT: '44',
    FLOATING_BAR_COUNT: '5',
    FLOATING_CLOSE_BUTTON: '1',
    FLOATING_THEME: 'professional_minimal',
    FLOATING_MOTION_PROFILE: 'expressive',
    FLOATING_GLOW_INTENSITY: '1.0',
    FLOATING_BAR_RADIUS: '1.0',
    FLOATING_BORDER_ALPHA: '72',
    RESET_TRANSCRIPT_EACH_RECORDING: '1',
    INSTANT_REFINE: '1',
    DICTATION_MODE: 'accurate',
    CLEANUP_LEVEL: 'aggressive',
    DEFAULT_TONE: 'polite',
    DEFAULT_LANGUAGE: 'english',
    ACTIVE_PROFILE: 'default',
    ACTIVE_APP: '',
    AUDIO_INPUT_DEVICE_ID: 'default',
    SAMPLE_RATE: '16000',
    CHANNELS: '1',
    TRIM_SILENCE: '1',
    SILENCE_THRESHOLD: '0.02',
    PERSONAL_DICTIONARY_PATH: '',
    SNIPPETS_PATH: '',
    PROFILE_BUNDLE_PATH: '',
    NVIDIA_WHISPER_MODEL: 'openai/whisper-large-v3',
    NVIDIA_CHAT_MODEL: 'nvidia/nemotron-3-8b-instruct',
    STREAMING_ENABLED: '1',
    STREAMING_CHUNK_DURATION: '1.5',
    STREAMING_CHUNK_OVERLAP: '0.3',
    STREAMING_MIN_CHUNKS: '2',
    STREAMING_FINAL_PASS: '1',
    MODE: 'dictation',
    AGENT_AUTO_DETECT: '1',
    AGENT_OUTPUT_FORMAT: 'structured',
    AGENT_WEBHOOK_URL: '',
    AGENT_IDE_INTEGRATION: '0',
    SPEC_MODE_ENABLED: '1',
    SPEC_TEMPLATE: 'standard',
    SPEC_AUTO_DETECT_INTENT: '1',
    SPEC_FORMAT: 'standard',
    SPEC_STORAGE_ENABLED: '1',
    AGENT_ENDPOINTS: '',
    WORKFLOW_FORMAT: 'openspec',
    CLI_AUTO_DETECT: '1',
    CLI_STRIP_NEWLINES: '1',
    CLI_NEWLINE_KEYWORD: 'new line',
    GRAMMAR_PRESERVE_CODE: '1',
    GRAMMAR_PRESERVE_TECHNICAL: '1',
    FLOATING_UI_STYLE: 'modern',
    FLOATING_ACCENT_COLOR: 'blue',
    FLOATING_GLASSMORPHISM: '1',
    FLOATING_ANIMATIONS: '1',
    FLOATING_REDUCED_MOTION: '0',
    FLOATING_LAYOUT: 'pill',
};

export const DEFAULT_DESKTOP_SETTINGS: DesktopSettings = desktopSettingDefaults;

export function getDefaultDesktopSettings(env: Record<string, string | undefined> = {}): DesktopSettings {
    const settings: DesktopSettings = {};

    for (const definition of DESKTOP_SETTING_DEFINITIONS) {
        const fallback = desktopSettingDefaults[definition.key] ?? '';
        const envValue = env[definition.key];
        settings[definition.key] = envValue ?? fallback;
    }

    return settings;
}
